# Generated by Django 5.2.17 on 2026-10-02 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Организация')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('bank_name', models.CharField(max_length=200, verbose_name='Банк')),
                ('bank_account', models.CharField(max_length=20, verbose_name='Расчётный счёт')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('contact_person', models.CharField(max_length=200, verbose_name='Контактное лицо')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Рейтинг')),
                ('price_per_minute', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость минуты рекламы, руб.')),
            ],
            options={
                'verbose_name': 'Передача',
                'verbose_name_plural': 'Передачи',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент от стоимости рекламы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рекламный агент',
                'verbose_name_plural': 'Рекламные агенты',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название ролика')),
                ('air_date', models.DateField(verbose_name='Дата выхода в эфир')),
                ('duration', models.PositiveIntegerField(verbose_name='Продолжительность, с')),
                ('description', models.TextField(verbose_name='Описание ролика')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата договора')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertising.agent', verbose_name='Агент')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertising.customer', verbose_name='Заказчик')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertising.program', verbose_name='Передача')),
            ],
            options={
                'verbose_name': 'Рекламный ролик',
                'verbose_name_plural': 'Рекламные ролики',
                'ordering': ['air_date'],
            },
        ),
    ]
